version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: ai_trader_postgres
    environment:
      POSTGRES_USER: trader
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ai_trader
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
